### ISSUE TITLE
no target spawn

### ISSUE THREAD

**Issue by MrAuronTV** [ESX-Brasil/esx_gunrange#1]
hi

when i start the game, no target spawn for me :/

**Comment by CMDTelhada** [comment]
Same for me
I start the challenge but the targets do not appear
:(

**Comment by psycodeliccircus** [comment]
Make the following settings

in config.lua
`Config.ChatMessages = false`
for
`Config.ChatMessages = true`

being also able to post the error log would be very good for me to help you!
@MrAuronTV @CMDTelhada

**Comment by MrAuronTV** [comment]
hi

i have no error in console : https://image.ibb.co/frjUP9/20180924141040_1.jpg
i have couldown when i start and nothing spawn after that

**Comment by psycodeliccircus** [comment]
Is not my script error and yes a menu_default error that you are using friend

http://prntscr.com/ky2i8i

**Comment by MrAuronTV** [comment]
but its original folder :o ?

menu for start works , i have coultdown but 0 targets after that :/

**Comment by psycodeliccircus** [comment]
I'm doing test here and it's working normally

**Comment by CMDTelhada** [comment]
I did what you suggested.
Set true
now on F8
I get this information so stay straight
http://prntscr.com/kyabsi

**Comment by MrAuronTV** [comment]
I have change the menu_default and dont work 😐

**Comment by jeanmateo** [comment]
I have the same problem :/

**Comment by CruelAlpha** [comment]
This script does not work, it does not spawn the targets.

**Comment by Local9** [comment]
Fix: https://github.com/ESX-Brasil/esx_gunrange/pull/2

**Comment by MrAuronTV** [comment]
Thx a lot !

**Comment by Local9** [comment]
@psycodeliccircus As you have now accepted the pull request this can be considered fixed and closed.
