### ISSUE TITLE
not working? 

### ISSUE THREAD

**Issue by SliderKP** [ESX-Brasil/esx_gunrange#4]
maybe because im using one sync?

**Comment by rafakid** [comment]
I'm the same

**Comment by HALALsnackbar** [comment]
Works with one-sync off but does not work with one-sync enabled.

**Comment by LoveFistRP** [comment]
I know the fix for this  I just don't know how to create a pull request

**Comment by alex070609** [comment]
Confirmed does not work with OneSync

**Comment by Oldarorn** [comment]
@alex070609 https://github.com/Oldarorn/old_gunrange

here you are, it's working but you'll need to add br language

**Comment by alex070609** [comment]
i'll look into into it

**Comment by psycodeliccircus** [comment]
New https://github.com/ESX-Brasil/old_gunrange
